### ISSUE TITLE
Breaks Google Inbox, stating error message related to U2F

### ISSUE THREAD

**Issue by medicalwei** [prefiks/u2f4moz#47]
When using Google Inbox with this extension, Google Inbox shows loading message at the bottom-left side forever, and cannot open any email.  Google sends a POST to their debug server pointing out that it might be the problem of u2f:

`https://inbox.google.com/u/0/jserror?script=blob:https://inbox.google.com/85af1506-6b15-3b44-b02b-449fb3eb402d&error=u2f is not a constructor&line=4847`

Disabling this extension makes Google Inbox work well.

**Comment by wiiaboo** [comment]
Also breaks some Google Docs spreadsheets, starting last week or so.

**Comment by prefiks** [comment]
I will look at fixing this this weekend, probably will need to add some kind of blacklist if i wouldn't find solution that will not trigger that exception...

**Comment by prefiks** [comment]
I can't reproduce that problem both with inbox and docs, probably if google serves code that causes that problem or not depends on some flag associated with account or browser.

I did prepare change that should allow overriding u2f object on page with value that is assigned by js code on google pages, that i hope will fix this problem, but since i am not able to reproduce this problem it would be great if someone who sees this problem could test it - i will publish url with version of this extension that will contains this fix in a second

**Comment by prefiks** [comment]
Url with test xpi: https://prefiks.github.io/u2f4moz/xpis/u2f-google-fix.xpi

**Comment by wiiaboo** [comment]
Seems to fix it with google spreadsheets, at least. I tried with a clean profile in DevEdition (since the addon was unsigned). Works with that build, but breaks with the current release: https://i.fsbn.eu/KXww.txt

**Comment by prefiks** [comment]
Thanks you! I will prepare proper release with that change later today.
